name: Build and Tag Docker Image

on:
  push:
    tags:
      - 'v*.*.*'  # Will match v1.2.3 but also v1.2.beta, so we'll filter in script

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Go dependencies
        run: |
          go mod tidy

      - name: Run Go tests
        run: go test ./...

      - name: Build and tag Docker image
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"  # e.g. v1.2.3
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')

          # Validate tag format v[major].[minor].[patch] where all are numbers
          if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag format invalid: $TAG_NAME"
            exit 0
          fi

          echo "Building Docker image for tag $TAG_NAME, commit $SHORT_SHA, time $TIMESTAMP"

          docker build \
            -t myorg/myimage:${TAG_NAME}-${SHORT_SHA}-${TIMESTAMP} \
            -t myorg/myimage:${TAG_NAME} \
            .

